import { useState } from 'react'
import { ArrowLeft, Edit3, MapPinned, Plus, Trash2, UsersRound, Map, CalendarDays, Home, Settings2, Image, Route, ShieldCheck } from 'lucide-react'
import { Modal } from '../components/Modal'
import { insertRow, updateRow, deleteRow } from '../services/data'
import { formatDate, formatTime, scheduleDate, scheduleTime, weekdayIndex, dayNames } from '../utils/constants'
import { generateSchedulePNG } from '../utils/png'

const tabs=[['dashboard','Visão geral',Settings2],['territories','Territórios',MapPinned],['areas','Áreas no mapa',Map],['groups','Grupos',UsersRound],['members','Membros',UsersRound],['locations','Locais',Home],['schedules','Programação',CalendarDays],['reports','Imagens / relatórios',Image]]

export function Admin({data,reload,setToast,onBack,onOpenMap}){
 const [tab,setTab]=useState('dashboard');const [modal,setModal]=useState(null);const [editing,setEditing]=useState(null)
 const save=async(table,payload,id)=>{try{if(id)await updateRow(table,id,payload);else await insertRow(table,payload);setModal(null);setEditing(null);setToast({message:'Alterações salvas com sucesso.'});await reload()}catch(e){setToast({type:'error',message:e.message})}}
 const remove=async(table,id)=>{if(!confirm('Excluir este item? Esta ação não pode ser desfeita.'))return;try{await deleteRow(table,id);setToast({message:'Item excluído.'});await reload()}catch(e){setToast({type:'error',message:e.message})}}
 const open=(type,value=null)=>{setEditing(value);setModal(type)}
 return <div className="admin-page"><header className="admin-head"><button className="icon-btn" onClick={onBack}><ArrowLeft/></button><div><span className="eyebrow">CONTROLE</span><h1>Painel Administrativo</h1><p className="admin-subtitle">Cadastre, organize e acompanhe todo o serviço de campo.</p></div></header><div className="admin-tabs">{tabs.map(([k,l,I])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}><I size={16}/>{l}</button>)}</div>
 {tab==='dashboard'&&<AdminDashboard data={data} onTab={setTab}/>} 
 {tab==='territories'&&<Territories data={data} onNew={()=>open('territory')} onEdit={x=>open('territory',x)} onDelete={x=>remove('territories',x)} onMap={t=>onOpenMap(t.id)}/>} 
 {tab==='areas'&&<Areas data={data} onMap={t=>onOpenMap(t.id)}/>} 
 {tab==='groups'&&<SimpleList title="Grupos" rows={data.groups} labelKey="name" onNew={()=>open('group')} onEdit={x=>open('group',x)} onDelete={x=>remove('field_groups',x)}/>} 
 {tab==='members'&&<Members data={data} onNew={()=>open('member')} onEdit={x=>open('member',x)} onDelete={x=>remove('members',x)}/>} 
 {tab==='locations'&&<SimpleList title="Locais de saída" rows={data.locations} labelKey="name" onNew={()=>open('location')} onEdit={x=>open('location',x)} onDelete={x=>remove('field_locations',x)}/>} 
 {tab==='schedules'&&<Schedules data={data} onNew={()=>open('schedule')} onEdit={x=>open('schedule',x)} onDelete={x=>remove('field_schedules',x)}/>} 
 {tab==='reports'&&<Reports data={data}/>} 
 {modal==='territory'&&<TerritoryForm value={editing} onClose={()=>setModal(null)} onSave={p=>save('territories',p,editing?.id)}/>} 
 {modal==='group'&&<GroupForm value={editing} onClose={()=>setModal(null)} onSave={p=>save('field_groups',p,editing?.id)}/>} 
 {modal==='member'&&<MemberForm value={editing} data={data} onClose={()=>setModal(null)} onSave={p=>save('members',p,editing?.id)}/>} 
 {modal==='location'&&<LocationForm value={editing} onClose={()=>setModal(null)} onSave={p=>save('field_locations',p,editing?.id)}/>} 
 {modal==='schedule'&&<ScheduleForm value={editing} data={data} onClose={()=>setModal(null)} onSave={p=>save('field_schedules',p,editing?.id)}/>} 
 </div>
}

function AdminDashboard({data,onTab}){const active=data.territories.filter(x=>x.active).length;const latest=data.history.filter(Boolean).length;return <div className="admin-content"><div className="stats-grid"><div className="admin-stat"><b>{active}</b><span>Territórios ativos</span></div><div className="admin-stat"><b>{data.members.filter(x=>x.active).length}</b><span>Membros ativos</span></div><div className="admin-stat"><b>{data.schedules.length}</b><span>Programações</span></div><div className="admin-stat"><b>{latest}</b><span>Registros de campo</span></div></div><div className="admin-dashboard-grid"><button className="admin-feature" onClick={()=>onTab('areas')}><MapPinned size={20}/><div><b>Delimitar territórios no mapa</b><span>Escolha um território e marque os pontos da área diretamente no mapa.</span></div></button><button className="admin-feature" onClick={()=>onTab('reports')}><Image size={20}/><div><b>Gerar imagem da programação</b><span>Crie uma imagem pronta para compartilhar com as informações do serviço.</span></div></button><button className="admin-feature" onClick={()=>onTab('schedules')}><CalendarDays size={20}/><div><b>Controlar programação</b><span>Defina dia, horário, local, dirigente, território e faixa de casas.</span></div></button><button className="admin-feature" onClick={()=>onTab('members')}><ShieldCheck size={20}/><div><b>Gerenciar equipe</b><span>Cadastre grupos, publicadores e dirigentes de campo.</span></div></button></div></div>}
function ActionHead({title,onNew}){return <div className="section-head"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h2>{title}</h2></div><button className="primary-small" onClick={onNew}><Plus size={16}/> Novo</button></div>}
function SimpleList({title,rows,labelKey,onNew,onEdit,onDelete}){return <div className="admin-content"><ActionHead title={title} onNew={onNew}/><div className="admin-list">{rows.map(r=><div className="admin-row" key={r.id}><div><b>{r[labelKey]}</b><span>{r.active?'Ativo':'Inativo'}</span></div><div className="row-actions"><button aria-label="Editar" onClick={()=>onEdit(r)}><Edit3 size={15}/></button><button aria-label="Excluir" onClick={()=>onDelete(r.id)}><Trash2 size={15}/></button></div></div>)}{!rows.length&&<div className="empty">Nenhum item cadastrado.</div>}</div></div>}
function Territories({data,onNew,onEdit,onDelete,onMap}){return <div className="admin-content"><ActionHead title="Territórios" onNew={onNew}/><div className="admin-list">{data.territories.map(t=><div className="admin-row" key={t.id}><div className="territory-admin"><i style={{background:t.color||'#6D45A6'}}/><div><b>{t.name}</b><span>{t.nickname||'Sem apelido'} · {t.active?'Ativo':'Inativo'} · {Array.isArray(t.polygon)?'Área definida':'Área não definida'}</span></div></div><div className="row-actions"><button title="Definir área no mapa" onClick={()=>onMap(t)}><Map size={15}/></button><button title="Editar" onClick={()=>onEdit(t)}><Edit3 size={15}/></button><button title="Excluir" onClick={()=>onDelete(t.id)}><Trash2 size={15}/></button></div></div>)}{!data.territories.length&&<div className="empty">Nenhum território cadastrado.</div>}</div></div>}
function Areas({data,onMap}){return <div className="admin-content"><div className="section-head"><div><span className="eyebrow">MAPA</span><h2>Áreas no mapa</h2><p>Defina visualmente os limites de cada território.</p></div></div><div className="admin-note"><MapPinned size={20}/><div><b>Como delimitar</b><span>Toque em um território abaixo. O mapa abrirá com ele selecionado; use “Desenhar território”, marque os pontos da área e salve.</span></div></div><div className="admin-list area-list">{data.territories.filter(t=>t.active).map(t=><button className="area-row" key={t.id} onClick={()=>onMap(t)}><span className="area-color" style={{background:t.color||'#6D45A6'}}/><div><b>{t.name}</b><small>{Array.isArray(t.polygon)?'Área já definida':'Ainda sem área no mapa'}</small></div><MapPinned size={17}/></button>)}{!data.territories.length&&<div className="empty">Cadastre um território primeiro.</div>}</div></div>}
function Members({data,onNew,onEdit,onDelete}){return <div className="admin-content"><ActionHead title="Membros" onNew={onNew}/><div className="admin-list">{data.members.map(m=><div className="admin-row" key={m.id}><div><b>{m.full_name}</b><span>{data.groups.find(g=>g.id===m.group_id)?.name||'Sem grupo'} · {m.member_type==='field_leader'?'Dirigente de campo':'Publicador'} · {m.active?'Ativo':'Inativo'}</span></div><div className="row-actions"><button onClick={()=>onEdit(m)}><Edit3 size={15}/></button><button onClick={()=>onDelete(m.id)}><Trash2 size={15}/></button></div></div>)}{!data.members.length&&<div className="empty">Nenhum membro cadastrado.</div>}</div></div>}
function Schedules({data,onNew,onEdit,onDelete}){const locs=new Map(data.locations.map(x=>[x.id,x.name])),terrs=new Map(data.territories.map(x=>[x.id,x.name])),leaders=new Map(data.members.map(x=>[x.id,x.full_name]));return <div className="admin-content"><ActionHead title="Programação" onNew={onNew}/><div className="admin-list">{data.schedules.slice(0,100).map(s=>{const d=scheduleDate(s);return <div className="admin-row" key={s.id}><div><b>{d?formatDate(d):(weekdayIndex(s)!==null?dayNames[weekdayIndex(s)]:'Dia não definido')} · {formatTime(scheduleTime(s))}</b><span>{locs.get(s.location_id)||'Sem local'} · {leaders.get(s.leader_id)||'Sem dirigente'} · {terrs.get(s.territory_id)||'Sem território'}</span></div><div className="row-actions"><button onClick={()=>onEdit(s)}><Edit3 size={15}/><span className="sr-only">Editar</span></button><button onClick={()=>onDelete(s.id)}><Trash2 size={15}/></button></div></div>})}{!data.schedules.length&&<div className="empty">Nenhuma programação cadastrada.</div>}</div></div>}
function Reports({data}){const locs=new Map(data.locations.map(x=>[x.id,x.name])),leaders=new Map(data.members.map(x=>[x.id,x.full_name])),terrs=new Map(data.territories.map(x=>[x.id,x.name]));return <div className="admin-content"><div className="section-head"><div><span className="eyebrow">COMPARTILHAMENTO</span><h2>Imagens da programação</h2><p>Gere uma imagem completa com os serviços cadastrados.</p></div></div><div className="report-card"><Image size={24}/><div><b>Programação completa</b><span>A imagem inclui dia, data, horário, local, dirigente, território, rua e faixa de números quando disponíveis.</span></div><button className="primary-small" onClick={()=>generateSchedulePNG(data.schedules.slice(0,30),locs,leaders,terrs)}><Image size={16}/> Gerar PNG</button></div></div>}
function FormShell({title,onClose,onSubmit,children}){return <Modal title={title} onClose={onClose}><form className="form-grid" onSubmit={onSubmit}>{children}<div className="modal-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancelar</button><button className="primary-btn">Salvar</button></div></form></Modal>}
function TerritoryForm({value,onClose,onSave}){return <FormShell title={value?'Editar território':'Novo território'} onClose={onClose} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:f.get('name'),nickname:f.get('nickname')||null,description:f.get('description')||null,color:f.get('color'),active:f.get('active')==='on'})}}><label>Nome oficial<input name="name" defaultValue={value?.name||''} required/></label><label>Apelido<input name="nickname" defaultValue={value?.nickname||''}/></label><label className="full">Descrição<textarea name="description" defaultValue={value?.description||''}/></label><label>Cor<input name="color" type="color" defaultValue={value?.color||'#6D45A6'}/></label><label className="check-label"><input name="active" type="checkbox" defaultChecked={value?.active??true}/> Ativo</label></FormShell>}
function GroupForm({value,onClose,onSave}){return <FormShell title={value?'Editar grupo':'Novo grupo'} onClose={onClose} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:f.get('name'),description:f.get('description')||null,active:f.get('active')==='on'})}}><label>Nome<input name="name" defaultValue={value?.name||''} required/></label><label>Descrição<input name="description" defaultValue={value?.description||''}/></label><label className="check-label"><input name="active" type="checkbox" defaultChecked={value?.active??true}/> Ativo</label></FormShell>}
function MemberForm({value,data,onClose,onSave}){return <FormShell title={value?'Editar membro':'Novo membro'} onClose={onClose} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({full_name:f.get('full_name'),group_id:f.get('group_id')||null,member_type:f.get('member_type'),active:f.get('active')==='on'})}}><label className="full">Nome completo<input name="full_name" defaultValue={value?.full_name||''} required/></label><label>Grupo<select name="group_id" defaultValue={value?.group_id||''}><option value="">Sem grupo</option>{data.groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label><label>Função<select name="member_type" defaultValue={value?.member_type||'publisher'}><option value="publisher">Publicador</option><option value="field_leader">Dirigente de campo</option></select></label><label className="check-label"><input name="active" type="checkbox" defaultChecked={value?.active??true}/> Ativo</label></FormShell>}
function LocationForm({value,onClose,onSave}){return <FormShell title={value?'Editar local':'Novo local'} onClose={onClose} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:f.get('name'),address:f.get('address')||null,active:f.get('active')==='on'})}}><label>Nome<input name="name" defaultValue={value?.name||''} required/></label><label>Endereço<input name="address" defaultValue={value?.address||''}/></label><label className="check-label"><input name="active" type="checkbox" defaultChecked={value?.active??true}/> Ativo</label></FormShell>}
function ScheduleForm({value,data,onClose,onSave}){const wi=weekdayIndex(value);return <FormShell title={value?'Editar programação':'Nova programação'} onClose={onClose} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const time=f.get('time');const weekday=Number(f.get('weekday'));onSave({weekday,weekday_name:dayNames[weekday],time,start_time:time||null,service_date:f.get('service_date')||null,location_id:f.get('location_id')||null,leader_id:f.get('leader_id')||null,territory_id:f.get('territory_id')||null,road_name:f.get('road_name')||null,number_start:f.get('number_start')?Number(f.get('number_start')):null,number_end:f.get('number_end')?Number(f.get('number_end')):null,note:f.get('note')||null,status:f.get('status')||'scheduled'})}}><label>Dia da semana<select name="weekday" defaultValue={wi??1}>{dayNames.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></label><label>Horário<input type="time" name="time" defaultValue={formatTime(scheduleTime(value))||'18:30'} required/></label><label>Data específica (opcional)<input type="date" name="service_date" defaultValue={value?.service_date||''}/></label><label>Local<select name="location_id" defaultValue={value?.location_id||''}><option value="">Sem local</option>{data.locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Dirigente<select name="leader_id" defaultValue={value?.leader_id||''}><option value="">Sem dirigente</option>{data.members.filter(x=>x.active&&x.member_type==='field_leader').map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Território<select name="territory_id" defaultValue={value?.territory_id||''}><option value="">Sem território</option>{data.territories.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Rua<input name="road_name" defaultValue={value?.road_name||''}/></label><label>Nº inicial<input name="number_start" type="number" defaultValue={value?.number_start??''}/></label><label>Nº final<input name="number_end" type="number" defaultValue={value?.number_end??''}/></label><label>Status<select name="status" defaultValue={value?.status||'scheduled'}><option value="scheduled">Programado</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select></label><label className="full">Observação<textarea name="note" defaultValue={value?.note||''}/></label></FormShell>}
